#data accessible application-wide
from .init import initialize

scopes = [
        'ActualTotalLoad',
        'AggregatedGenerationPerType',
        'DayAheadTotalLoadForecast' ]

resolutions = { 
        'PT60M' : '1', 
        'PT15M' : '2', 
        'PT30M' : '3' }

inv_resolutions = { 
        '2': 'PT15M', 
        '1': 'PT60M', 
        '3': 'PT30M' }

prod_types = { 
        '1': 'Fossil Gas', 
        '2': 'Hydro Run-of-river and poundage', 
        '3': 'Hydro Pumped Storage', 
        '4': 'Hydro Water Reservoir', 
        '5': 'Fossil Hard coal', 
        '6': 'Nuclear', 
        '7':'Fossil Brown coal/Lignite', 
        '8':'Fossil Oil', 
        '9':'Fossil Oil shale', 
        '10':'Biomass', 
        '11':'Fossil Peat', 
        '12':'Wind onshore', 
        '13':'Other', 
        '14':'Wind offshore', 
        '15':'Fossil Coal-derived gas', 
        '16':'Waste', 
        '17':'Solar', 
        '18':'Geothermal',
        '19':'Other renewable', 
        '20':'Marine', 
        '21':'AC Link', 
        '22':'Transformer', 
        '23':'DC Link', 
        '24':'Substation' }

area_type_codes = {
        '1':'CTA',
        '2':'BZN',
        '3':'CTY',
        '4':'MBA',
        '5':'BZA' }
map_codes = {
        '1':'BE',
        '2':'FI',
        '3':'LU',
        '4':'FR',
        '5':'PT',
        '6':'AT',
        '7':'DE_AT_LU',
        '8':'HU',
        '9':'NO5',
        '10':'NO2',
        '11':'NO4',
        '12':'NO1',
        '13':'NO3',
        '14':'NO',
        '15':'LV',
        '16':'DE_Amprion',
        '17':'SE3',
        '18':'SE1',
        '19':'SE2',
        '20':'SE4',
        '21':'DE_TenneT_GER',
        '22':'EE',
        '23':'GR',
        '24':'ES',
        '25':'SK',
        '26':'SI',
        '27':'DE_TransnetBW',
        '28':'NL',
        '29':'GB',
        '30':'CZ',
        '31':'PL',
        '32':'DK2',
        '33':'DK1',
        '34':'CH',
        '35':'HR',
        '36':'DE',
        '37':'ME',
        '38':'DE_50HzT',
        '39':'BG',
        '40':'DK',
        '41':'IT_SUD',
        '42':'IT_NORD',
        '43':'SE',
        '44':'IT_CNOR',
        '45':'IT',
        '46':'IT_SICI',
        '47':'IT_CSUD',
        '48':'IT_SARD',
        '49':'IT_North',
        '50':'LT',
        '51':'IE',
        '52':'IE_SEM',
        '53':'NIE',
        '54':'RS',
        '55':'AL',
        '56':'RO',
        '57':'MK',
        '58':'CY',
        '59':'BA',
        '60':'UA_BEI',
        '61':'UA',
        '62':'UA_IPS',
        '63':'DE_LU',
        '65':'IT_PRGP',
        '66':'IT_ROSN',
        '68':'IT_FOGN',
        '69':'IT_BRNN',
        '70':'RU',
        '71':'IT_SACO_DC',
        '72':'BY',
        '73':'RU_KGD',
        '74':'TR',
        '75':'IT_NORD_AT',
        '76':'IT_GR',
        '77':'IT_NORD_CH',
        '78':'CZ_DE_SK',
        '79':'IT_NORD_FR',
        '80':'IT_NORD_SI',
        '81':'IT_SACO_AC',
        '82':'UA_DobTPP',
        '83':'MT',
        '84':'MD',
        '85':'IT_SICI_MT',
        '275':'PL_CZ',
        '277':'LT-SE4' }


app, mysql, blacklist = initialize()
